services:
  shopware:
    container_name: shopware
    image: dockware/shopware:6.6.10.11
    ports:
      - 80:80
    volumes:
      - 'shopware-data:/var/www/html'
      - 'db-data:/var/lib/mysql'
      - './ArnowaProductComplianceInfo:/var/www/html/custom/plugins/ArnowaProductComplianceInfo'
volumes:
  shopware-data:
    driver: local
  db-data:
    driver: local
